name: Continuous Integration

on:
  pull_request:
    branches: [dev]

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: AlexxNB/caprover-action@v1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'bdx-2021-03-js-buzzle'
