name: Continuous Integration

on:
  push:
    branches:    
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: AlexxNB/caprover-action@v1
        with:
          branch: develop
          server: '${{ secrets.CAPROVER_SERVER }}'
          password: '${{ secrets.CAPROVER_PASSWORD }}'
          appname: 'bdx-2021-03-js-buzzle'
